### ISSUE TITLE
Question about the workflow

### ISSUE THREAD

**Issue by abovzv** [Mashin6/orthogonalize-polygon#1]
Hi, thanks for your great job.
I tried it with my geo-data, and it really performs well. However, it's hard for me to understant the whole workflow, especially the roration.
Any paper can I read about to know more?
Thanks~

**Comment by Mashin6** [comment]
I took the idea from [JOSM](https://josm.openstreetmap.de/) project. Not sure if it is based on any publication.

The rotation is there only to roughly align the all edges of polygon with x (west-east) and y (north-south) axes. That way it's much easier to achieve 90˚ angles. You just have to move the polygon nodes to make all edges parallel to x or y axis and all angles automatically become either 90˚ or 180 ˚.

1. Calculate angle between each edge and x/y axis. 
2. Rotate polygon by median of angles to align to x-y axes.
3. Move nodes to make segments parallel to x-y axes: 
horizontal segment: adjust the two nodes y coordinates to their mean value
vertical segment: adjust their two nodes x coordinates to thier mean value
4. Rotate polygon back

<img width="476" alt="image" src="https://user-images.githubusercontent.com/5265707/195704072-75489782-662f-4ae2-bc23-507836938acf.png">

**Comment by abovzv** [comment]
It reminds me a lot, thanks!
